"use client";
import { useState } from "react";
import { MessageSquare, Plus, Users, X } from "lucide-react";
import InternalMessagePanel from "@/components/messaging/InternalMessagePanel";
import type { ConversationSummary, InternalConversation, MessagingEmployee } from "@/components/messaging/types";
type Props = { initialConversations: ConversationSummary[]; currentEmployee: MessagingEmployee; employees: MessagingEmployee[] };
export default function InternalMessagesDashboard({ initialConversations, currentEmployee, employees }: Props) {
  const [conversations, setConversations] = useState(initialConversations); const [open, setOpen] = useState<InternalConversation | null>(null); const [newOpen, setNewOpen] = useState(false);
  const directUnread = conversations.filter((item) => item.conversation_type === "internal_direct").reduce((sum, item) => sum + item.unread_count, 0);
  const jobUnread = conversations.filter((item) => item.conversation_type === "internal_job").reduce((sum, item) => sum + item.unread_count, 0); const mentions = conversations.reduce((sum, item) => sum + item.mention_count, 0);
  async function select(summary: ConversationSummary) { const response = await fetch(`/api/internal-messages?conversationId=${encodeURIComponent(summary.id)}`, { cache: "no-store" }); const data = await response.json(); if (response.ok) { setOpen(data.conversation); setConversations((items) => items.map((item) => item.id === summary.id ? { ...item, unread_count: 0, mention_count: 0 } : item)); } }
  async function create(type: "internal_direct" | "internal_group", participantIds: string[], title?: string) { const response = await fetch("/api/internal-messages", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "create_conversation", type, participantIds, title }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setOpen(data.conversation); setNewOpen(false); setConversations((items) => [data.conversation, ...items.filter((item) => item.id !== data.conversation.id)]); }
  return <><section className="rounded-xl border border-gray-200 bg-white p-6 shadow-sm xl:col-span-2"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-xl font-semibold">Internal Messages</h2><p className="mt-1 text-sm text-gray-500">Direct, group, and assigned-job conversations.</p></div><button type="button" onClick={() => setNewOpen(true)} className="inline-flex items-center gap-2 rounded-lg bg-black px-4 py-2 text-sm font-medium text-white"><Plus className="size-4" />New Message</button></div><div className="mt-4 flex flex-wrap gap-2"><Badge label="Direct unread" count={directUnread} /><Badge label="Job unread" count={jobUnread} /><Badge label="Mentions" count={mentions} mention /></div><div className="mt-5 divide-y divide-gray-100">{conversations.length ? conversations.slice(0, 10).map((item) => <button key={item.id} type="button" onClick={() => void select(item)} className="grid w-full gap-2 py-3 text-left hover:bg-gray-50 sm:grid-cols-[minmax(0,1fr)_auto] sm:px-2"><div className="min-w-0"><div className="flex items-center gap-2"><MessageSquare className="size-4 text-gray-400" /><p className="truncate font-medium text-gray-900">{item.title}</p></div><p className="mt-1 truncate text-sm text-gray-500">{item.last_message ?? "No messages yet"}</p></div><div className="flex items-center gap-2 text-xs text-gray-500">{item.mention_count ? <span className="rounded-full bg-purple-100 px-2 py-1 font-semibold text-purple-700">@{item.mention_count}</span> : null}{item.unread_count ? <span className="rounded-full bg-black px-2 py-1 font-semibold text-white">{item.unread_count}</span> : null}<span>{item.last_message_at ? new Date(item.last_message_at).toLocaleDateString([], { month: "short", day: "numeric" }) : ""}</span></div></button>) : <p className="py-8 text-center text-sm text-gray-500">No internal conversations yet.</p>}</div></section>{open ? <div className="fixed inset-0 z-50 bg-black/30" onMouseDown={(event) => { if (event.target === event.currentTarget) setOpen(null); }}><aside className="ml-auto h-full w-full max-w-xl overflow-y-auto bg-white p-4 shadow-2xl"><InternalMessagePanel initialConversation={open} currentEmployee={currentEmployee} employees={employees} jobId={open.job_id ?? undefined} onClose={() => setOpen(null)} /></aside></div> : null}{newOpen ? <NewConversation employees={employees.filter((item) => item.id !== currentEmployee.id)} onClose={() => setNewOpen(false)} onCreate={create} /> : null}</>;
}
function Badge({ label, count, mention = false }: { label: string; count: number; mention?: boolean }) { return <span className={`rounded-full px-3 py-1 text-xs font-semibold ${count ? mention ? "bg-purple-100 text-purple-700" : "bg-gray-900 text-white" : "bg-gray-100 text-gray-500"}`}>{label}: {count}</span>; }
function NewConversation({ employees, onClose, onCreate }: { employees: MessagingEmployee[]; onClose: () => void; onCreate: (type: "internal_direct" | "internal_group", ids: string[], title?: string) => Promise<void> }) { const [group, setGroup] = useState(false); const [selected, setSelected] = useState<string[]>([]); const [title, setTitle] = useState(""); const [error, setError] = useState(""); return <div className="fixed inset-0 z-[60] flex items-center justify-center bg-black/40 p-4"><div className="w-full max-w-md rounded-xl bg-white p-6 shadow-xl"><div className="flex justify-between"><div><h3 className="text-lg font-semibold">New Internal Message</h3><p className="mt-1 text-sm text-gray-500">Visible only to selected employees.</p></div><button type="button" onClick={onClose}><X className="size-5" /></button></div><label className="mt-5 flex items-center gap-2 text-sm"><input type="checkbox" checked={group} onChange={(event) => { setGroup(event.target.checked); setSelected([]); }} />Group conversation</label>{group ? <input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Group name" className="mt-3 w-full rounded-lg border border-gray-300 px-3 py-2" /> : null}<div className="mt-4 max-h-64 space-y-2 overflow-auto">{employees.map((employee) => <label key={employee.id} className="flex items-center gap-3 rounded-lg border border-gray-200 p-3"><input type={group ? "checkbox" : "radio"} name="employee" checked={selected.includes(employee.id)} onChange={() => setSelected((current) => group ? current.includes(employee.id) ? current.filter((id) => id !== employee.id) : [...current, employee.id] : [employee.id])} /><Users className="size-4 text-gray-400" /><span className="text-sm font-medium">{employee.name}</span></label>)}</div>{error ? <p className="mt-3 text-sm text-red-700">{error}</p> : null}<div className="mt-5 flex justify-end gap-2"><button type="button" onClick={onClose} className="rounded-lg border px-4 py-2 text-sm">Cancel</button><button type="button" onClick={() => void onCreate(group ? "internal_group" : "internal_direct", selected, title).catch((reason) => setError(reason instanceof Error ? reason.message : "Unable to create conversation."))} className="rounded-lg bg-black px-4 py-2 text-sm font-medium text-white">Start</button></div></div></div>; }
