"use client";

import { useState } from "react";
import { Eye, Pencil, Plus, Send } from "lucide-react";
import { saveTemplate, testTemplate, toggleTemplate } from "@/app/actions/email-templates";
import { EMAIL_MERGE_FIELDS, type EmailTemplate } from "@/components/email/types";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

export default function EmailTemplatesManager({ initialTemplates }: { initialTemplates: EmailTemplate[] }) {
  const [templates, setTemplates] = useState(initialTemplates); const [editing, setEditing] = useState<EmailTemplate | null | undefined>();
  const [preview, setPreview] = useState<EmailTemplate | null>(null); const [testEmail, setTestEmail] = useState("");
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  async function toggle(item: EmailTemplate) { setBusy(true); try { await toggleTemplate(item.id, !item.active); setTemplates((all) => all.map((x) => x.id === item.id ? { ...x, active: !x.active } : x)); } finally { setBusy(false); } }
  async function test(item: EmailTemplate) { if (!testEmail) { setMessage("Enter a test recipient first."); return; } setBusy(true); setMessage(""); try { await testTemplate(item.id, testEmail); setMessage(`Test email sent for ${item.name}.`); } catch (e) { setMessage(e instanceof Error ? e.message : "Test send failed."); } finally { setBusy(false); } }
  return <>
    <section className="mt-8 rounded-xl border border-gray-200 bg-white shadow-sm"><div className="flex flex-col gap-4 border-b p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-xl font-semibold">Email Templates</h2><p className="mt-1 text-sm text-gray-500">Reusable manual and pipeline automation messages.</p></div><Button onClick={() => setEditing(null)}><Plus/>New Template</Button></div>
      <div className="border-b p-5"><label className="grid max-w-md gap-2 text-sm font-medium">Test recipient<Input type="email" value={testEmail} onChange={(e) => setTestEmail(e.target.value)} placeholder="you@bramflooring.com"/></label>{message ? <p className="mt-2 text-sm text-gray-600">{message}</p> : null}</div>
      <div className="divide-y">{templates.map((item) => <article key={item.id} className="flex flex-col gap-4 p-5 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold">{item.name}</h3><span className="rounded-full bg-gray-100 px-2 py-1 text-xs">{item.category}</span><span className={`rounded-full px-2 py-1 text-xs font-semibold ${item.active ? "bg-green-50 text-green-700" : "bg-gray-100 text-gray-500"}`}>{item.active ? "Enabled" : "Disabled"}</span></div><p className="mt-1 text-sm text-gray-500">{item.subject}</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => setPreview(item)}><Eye/>Preview</Button><Button variant="outline" onClick={() => void test(item)} disabled={busy}><Send/>Test</Button><Button variant="outline" onClick={() => setEditing(item)}><Pencil/>Edit</Button><Button variant="outline" onClick={() => void toggle(item)} disabled={busy}>{item.active ? "Disable" : "Enable"}</Button></div></article>)}</div>
    </section>
    {editing !== undefined ? <TemplateEditor template={editing} onClose={() => setEditing(undefined)} onSaved={(saved) => { setTemplates((all) => editing ? all.map((item) => item.id === saved.id ? saved : item) : [...all, saved]); setEditing(undefined); }}/>: null}
    {preview ? <Modal title={preview.name} onClose={() => setPreview(null)}><p className="text-sm font-semibold">{preview.subject}</p><p className="mt-4 whitespace-pre-wrap text-sm leading-6 text-gray-700">{preview.body}</p></Modal> : null}
  </>;
}

function TemplateEditor({ template, onClose, onSaved }: { template: EmailTemplate | null; onClose: () => void; onSaved: (value: EmailTemplate) => void }) {
  const [name,setName]=useState(template?.name??""); const [category,setCategory]=useState(template?.category??"General"); const [subject,setSubject]=useState(template?.subject??""); const [body,setBody]=useState(template?.body??""); const [active,setActive]=useState(template?.active??true); const [error,setError]=useState(""); const [saving,setSaving]=useState(false);
  async function submit(e: React.FormEvent) { e.preventDefault(); setSaving(true); setError(""); try { onSaved(await saveTemplate(template?.id??null,{name,category,subject,body,active})); } catch(caught){setError(caught instanceof Error?caught.message:"Unable to save template.");} finally{setSaving(false);} }
  return <Modal title={template ? "Edit Email Template" : "New Email Template"} onClose={onClose}><form onSubmit={submit} className="grid gap-4"><label className="grid gap-1 text-sm font-medium">Name<Input value={name} onChange={(e)=>setName(e.target.value)}/></label><label className="grid gap-1 text-sm font-medium">Category<Input value={category} onChange={(e)=>setCategory(e.target.value)}/></label><label className="grid gap-1 text-sm font-medium">Subject<Input value={subject} onChange={(e)=>setSubject(e.target.value)}/></label><label className="grid gap-1 text-sm font-medium">Body<textarea rows={12} value={body} onChange={(e)=>setBody(e.target.value)} className="rounded-lg border p-3 text-sm"/></label><div className="flex flex-wrap gap-2">{EMAIL_MERGE_FIELDS.map((field)=><button type="button" key={field} onClick={()=>setBody((value)=>`${value}{{${field}}}`)} className="rounded bg-gray-100 px-2 py-1 text-xs font-medium">{`{{${field}}}`}</button>)}</div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={active} onChange={(e)=>setActive(e.target.checked)}/>Enabled</label>{error?<p className="text-sm text-red-700">{error}</p>:null}<div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={onClose}>Cancel</Button><Button disabled={saving}>{saving?"Saving...":"Save Template"}</Button></div></form></Modal>;
}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-4"><div className="max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-xl bg-white p-6 shadow-xl"><div className="mb-5 flex items-center justify-between"><h2 className="text-xl font-semibold">{title}</h2><button onClick={onClose} className="text-sm text-gray-500">Close</button></div>{children}</div></div>}
